FROM node:latest
COPY package*.json ./
ENV PORT=4000
ENV NODE_ENV=DEVELOPMENT
ENV DB_LOCAL_URI=mongodb+srv://akshaya:akshaya@cluster0.8kzmz1j.mongodb.net/Petstore?retryWrites=true&w=majority
ENV JWT_SECRET=OIJFUHRIGIH46846JRIOJORI464698NASIU
ENV JWT_EXPIRES_TIME=7d
ENV COOKIE_EXPIRES_TIME=7
ENV CLOUDINARY_CLOUD_NAME=dzigorjli
ENV CLOUDINARY_API_KEY=199963386889976
ENV CLOUDINARY_API_SECRET=MsWRLtWREslzR66vxeuYPZse6wM
ENV STRIPE_SECRET_KEY=sk_test_51MzfDXSJEFUnCtRHYKQcByqfnOwJt7VsRyIeY6qB8jOUZsGb45sxdjNwMxO7QPniAIP4FJFghmdQIQ00QJAQTkyk00WCljgLdu
ENV STRIPE_API_KEY=pk_test_51MzfDXSJEFUnCtRHivNfrOKB2PnGItypYXTDe56wbsmHvP3vxArI3ZkkPTZDbTpqxeF8vfi3w2AfdWVnMy5z0erc00Z6sryNh8
RUN npm install
COPY . .
EXPOSE 4000
CMD ["npm","start"]